### PR TITLE
Fixes Issue #9

### PR DESCRIPTION
**Pull request by haidangwa**
### Description
- set chef_ingredient action to `:install` when an explicit version is found; `:upgrade` otherwise
### Issues Resolved

Fixes Issue [#9](https://github.com/chef-cookbooks/chef-analytics/issues/9)
### Check List
- [x] All tests pass. See https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable
- [x] The CLA has been signed. See https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD

### CODE REVIEW

**Comment by tas50** [comment]
@haidangwa Can you rebase this? Also what's the need for kitchen-sync?

**Comment by haidangwa** [comment]
@tas50 I noticed that several gems were removed in recent commits. They were gems used for testing in Test Kitchen. Are they no longer needed? kitchen-sync speeds up file transfers between Test Kitchen instances and the local development workstation.

**Comment by tas50** [comment]
We moved to testing with chefdk vs. constantly bumping the gems.  It removed a huge amount of busy work I was doing.

**Comment by tas50** [comment]
Also can you squash this and sign it for the DCO. There's details if by the DCO status here

**Comment by tas50** [comment]
Thanks

**Pull request merged**
